 
CREATE TABLE IF NOT EXISTS event_data (
  event_data_id serial not null, 
  event_date date NOT NULL  			,
  id VARCHAR(45) NULL,
  device_id VARCHAR(45) NULL,
  hub_id VARCHAR(45) NULL,
  location_id VARCHAR(45) NULL,
  installed_smart_app_id VARCHAR(45) NULL,
  is_state_change VARCHAR(45) NULL,
  is_physical VARCHAR(45) NULL,
  description VARCHAR(45) NULL,
  description_text VARCHAR(45) NULL,
  display_name VARCHAR(45) NULL,
  iso_date VARCHAR(45) NULL,
  name VARCHAR(45) NULL,
  unit VARCHAR(45) NULL,
  source VARCHAR(45) NULL,
  value VARCHAR(45) NULL,
  string_value VARCHAR(45) NULL,
  integer_value INT NULL,
  long_value VARCHAR(45) NULL,
  float_value FLOAT NULL,
  double_value float NULL,
  number_value DECIMAL(32) NULL,
  numeric_value DECIMAL(32) NULL,
  date_value date NULL,
  xyz_value VARCHAR(45) NULL,
  json_value VARCHAR(45) NULL,
  PRIMARY KEY (event_data_id));